# Global parameters

[global]

```
interfaces = lo enp0s1
bind interfaces only = yes

dns forwarder = 192.168.64.1

netbios name = UBUNTU01

realm = LAB.LOCAL

server role = active directory domain controller

workgroup = LAB

idmap_ldb:use rfc2307 = yes
```

[sysvol]

```
path = /var/lib/samba/sysvol

read only = No
```

[netlogon]

```
path = /var/lib/samba/sysvol/lab.local/scripts

read only = No
```
